
# Example Invocation:
# END=2019-06-11T23:59:59Z sparql-integrate --u --w=trig/pretty wikidata-sample.trig extract-one-week-from-log.sparql

CONSTRUCT {
  GRAPH ?g {
    ?a ?b ?c .
    ?c ?d ?e
  }
}
#SELECT ?dt
{
  GRAPH ?g {
    ?a prov:atTime ?t .
    # Substracting timestamps gives an xsd:duration, and at least Jena seems to yield the duration's full days with the DAY function
    # Note that sparql 12 discussion is about standardizing this: https://github.com/w3c/sparql-12/issues/32
    BIND(DAY(STRDT(<env:END>, xsd:dateTime) - ?t) AS ?dt)
    FILTER(?dt < 7)

    # Unfortunately, standard sparql does not seem to support sorted construct output: https://www.w3.org/TR/rdf-sparql-query/#SolModandCONSTRUCT
    # ?a <http://lsq.aksw.org/vocab#sequenceId> ?seqId .

    ?a ?b ?c 
    OPTIONAL { ?c ?d ?e }
  }
}

