# Return the unique queries in lsq data
# Use sparql-integrate with '-u' flag to scan over named graphs

PREFIX lsq: <http://lsq.aksw.org/vocab#>
CONSTRUCT {
  GRAPH ?g { ?s lsq:text ?str }
}
{
  { SELECT DISTINCT ?str {
    GRAPH ?g { ?s lsq:text ?str }
  } ORDER BY ?str }
  BIND(SHA256(?str) AS ?hash)
  BIND(BNODE(?hash) AS ?s)
  BIND(IRI(CONCAT('urn:sha256:', ?hash)) AS ?g)
}

