SELECT DISTINCT  ?c
WHERE
  { { SELECT  (count(*) AS ?c)
      WHERE
        { SELECT DISTINCT  ?x0
          WHERE
            { ?x0  <http://dbpedia.org/ontology/starring>  <http://dbpedia.org/resource/Matthew_Fox>}
        }
    }
  }
