SELECT  (count(*) AS ?c)
WHERE
  { <http://dbpedia.org/resource/Matthew_Fox>
              <http://dbpedia.org/ontology/birthPlace>  <http://dbpedia.org/resource/Abington_Township,_Montgomery_County,_Pennsylvania>}
